 envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: flixora-db
          property: connectionString
  
      - key: SECRET_KEY
        generateValue: true
      - key: ENCRYPTION_KEY
@@ -21,7 +18,3 @@ services:
        sync: false
      - key: TEST_MODE
        value: "true"

databases:
  - name: flixora-db
    plan: free
